services:
  - type: web
    name: sillytavern
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
